### PR TITLE
Improve Dockerfile

### PR DESCRIPTION
**Pull request by Nargonath**
As I mentioned in the issues I opened, I wrote my own Dockerfile and I figured I'd share the improvements I made:

* I updated the base Debian image to use latest.
* I updated the Python version shipped with the Debian image to latest.
* I updated the version downloaded of Arango client to 3.11 as 3.9 is deprecated.
* Debian bookworm ships with `curl` so I used it to download arango client instead of installing `wget`.
* I added two arguments for userId and groupId because when you generate migrations through the docker image they're owned by `root` which prevents host user to modify them. By either providing `$(id -u)` and `$(id -g)` to the build-args or using the default values (if they match), the current host user will own the created files.
* I used `pip` to install `migrado` instead of `peotry` as it seems simpler and allows the user to bind mount his project root under `/app` as well because it doesn't rely on the TOML file to be present. As I'm not a Python developer perhaps this was a mistake.

### CODE REVIEW

**Comment by tangram** [comment]
Thanks for the pull request, these are all good improvements. Accepted if README.md and LICENCE.txt are copied into the Dockerfile.

**Comment by Nargonath** [comment]
Alright, sure I'll make the fix.

**Comment by tangram** [comment]
I changed the base image to `python:3.12-slim-bookworm`, as I remembered this was to keep the image size down, and also the reason why wget was installed.

Otherwise, the image is available on Docker Hub as `protojour/migrado:0.6.11` and `:latest`.

**Comment by Nargonath** [comment]
Alright, makes sense. Thank you.

**Pull request merged**
